name: Deploy NPM package

on:
  push:
    branches:
      - main

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - run: ./.github/increment-version.sh -p
      - run: npm install
      - run: npm run build
      - run: cp ./package.json ./dist/package.json
      - run: cp ./README.md ./dist/README.md
      - run: sed -i.bak "s/dist\///" ./dist/package.json
      - run: npm publish dist
